language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="1.0.x-dev"
    - DB=MYSQL

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.1.2
      env: PHPUNIT_TEST=1

before_script:
# Init PHP
  - if [[ $PHPCS_TEST ]]; then pyrus install pear/PHP_CodeSniffer; fi
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer install --prefer-dist
  - composer require --prefer-dist --no-update symfony/config:^3.2 silverstripe/recipe-core:1.0.x-dev
  - composer update

script:
 - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests; fi
 - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
